version: "3.4"

x-app-volumes:
  &app-volumes
  - .:/app
  - ~/.bash_history:/root/.bash_history
  - ~/.irbrc:/root/.irbrc

services:
  app:
    build: .
    volumes: *app-volumes
    stdin_open: true
    tty: true
    command: bundle exec falcon serve --bind http://0.0.0.0:9292
    ports:
      - 3000:9292
