version: "3.4"

x-app-volumes:
  &app-volumes
  - .:/app
  - bundle:/app/vendor/bundle
  - ~/.bash_history:/root/.bash_history
  - ~/.irbrc:/root/.irbrc

services:
  app:
    build: .
    volumes: *app-volumes
    stdin_open: true
    tty: true
    command: bundle exec falcon host
    depends_on:
      - db
    ports:
      - 3000:80
    networks:
      - external
      - internal

  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_DB: bookshelf_development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

volumes:
  bundle:
  postgres-data:
